version: '3.8'

services:
  kajiapp:
    build:
      context: ./kajiApp 
      dockerfile: Dockerfile
    volumes:
      - ./kajiApp/flaskr/static:/app/flaskr/static
    container_name: kajiapp
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - app-network
    restart: always   
networks:
  app-network:
    driver: bridge
