version: '3'
services:
  flask-app:
    image: housework-flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./flaskr:/app/flaskr
    environment:
      FLASK_ENV: development
    restart: always  # Docker起動時に自動起動する設定